# DarkAC konfigurační soubor
spam:
  chat:
    # Měl by DarkAC blokovat spamování zprávy v chatu?
    block-speed: true
    block-repetition: true
    # Platné akce = NONE,KICK,BAN,COMMAND[příkaz]
    action-one: KICK
    action-two: BAN
  # Měl by DarkAC blokovat spamování příkazů v chatu?
  command:
    block-speed: true
    block-repetition: true
    # Platné akce = NONE,KICK,BAN,COMMAND[příkaz]
    action-one: KICK
    action-two: BAN
system:
  # Měl by být DarkAC logovat všechny neúspěšné kontroly do konzole?
  log-to-console: false
  # Měl by být DarkAC logovat do souboru?
  log-to-file: true
  # Měl by být DarkAC zobrazovat další informace ladění při startu?
  verbose-startup: false
  # Pokud je tichý režim zapnutý, hráči nebudou blokováni, když se snaží hackovat a DarkAC udělá vše, co je možné udržet si vědomí jejich rostoucí úrovně hackingu.
  # Nicméně, výstrahy budou odeslány do konzole a jakémukoliv online administrátorovi a události budou stále probíhat.
  silent-mode: false
  # Zakázat vysílání o tom, proč byl hráč vyhozen
  disable-broadcast: false
  # Měl by být OP hráč osvobozen od všech kontrol?
  exempt-op: false
  # Měl by DarkAC trackovat ve vlastních registrovaných událostech?
  event-chains: true
  # Měly by být povoleny možnosti podnikání? Pokud jste rozšířeným uživatelem, nastavte pouze true.
  enterprise: false
  # Běží-li DarkAC v režimu ladění odešle upozornění na podvádění hráčů a umožnit protokolování ladění
  # Použijte toto při lokalizaci nebo hlášení falešně pozitivy nebo při testování DarkAC
  # Nepovolujte to v podnikatelském prostředí!
  debug-mode: false
  # Aby se zabránilo spamování, personál a konzole budou informovány pouze každým porušením
  # Minimální hodnota je 1, výchozí je 8
  # Příklad s 5: Oznámení po 5 VL, 10VL, 15VL atd.
  notify-every-vl: 8
  # Maximální vzdálenost setbacku lze nastavit
  # Pokud je poslední známé platné umístění dál než toto,
  # Setback bude gumenbanded na jejich aktuální poloze
  # Minimální hodnota je 5, výchozí je 50
  max-setback-distance: 50
disable-in:
- example-world
- example-world-2
