name: DarkAC
author: DarkReaper231
description: DarkAC pomáhá snadno identifikovat a blokovat cheatery na vašem serveru.
main: com.rammelkast.anticheatreloaded.AntiCheatReloaded
api-version: 1.13
depend: [ProtocolLib]
softdepend: [Floodgate, floodgate]
startup: postworld
version: ${project.build.version}
commands:
  anticheat:
    description: Ovládání a zobrazení informací o DarkAC
    usage: /anticheat help
    aliases: dac
permissions:
  anticheat.system.notice:
    description: Přístup ke zprávám, když je hráč vykopnut nebo zabanován za hackování
  anticheat.system.alert:
    description: Přístup k upozornění, když hráč podvádí
  anticheat.system.help:
    description: Přístup k příkazu help
  anticheat.system.mute:
    description: Přístup k funkci ztlumení
  anticheat.system.report:
    description: Přístup k cheat zprávám
  anticheat.mod:
    description: Mod helper perm
    children:
      anticheat.system.notice: true
      anticheat.system.alert: true
      anticheat.system.help: true
      anticheat.system.report: true
      anticheat.system.mute: true
  anticheat.system.log:
    description: Přístup k zapnutí nebo vypnutí hlášení do konzole
  anticheat.system.reload:
    description: Přístup k opětovnému načtení systému
  anticheat.system.reset:
    description: Přístup k resetování úrovně podvádění hráče
  anticheat.system.version:
    description: Přístup k informacím o tom, zda je systém aktualizován
  anticheat.admin:
    description: Admin helper perm
    children:
      anticheat.mod: true
      anticheat.system.log: true
      anticheat.system.reload: true
      anticheat.system.reset: true
      anticheat.system.mute: true
  anticheat.check.flight:
    description: Dovoluje hráčům používat fly
    default: false
  anticheat.check.elytrafly:
    description: Dovoluje hráčům používat ElytraFly
    default: false
  anticheat.check.waterwalk:
    description: Dovluje hráčům jesus
    default: false
  anticheat.check.fastplace:
    description: Dovoluje hráčům používat build hacky and fastplace
    default: false
  anticheat.check.chatspam:
    description: Dovluje hráčům spamovat
    default: false
  anticheat.check.commandspam:
    description: Dovluje hráčům spamovat příkazy
    default: false
  anticheat.check.sprint:
    description: Dovluje hráčům sprintovat hladoví
    default: false
  anticheat.check.sneak:
    description: Dovoluje hráčům používat sneak hacky
    default: false
  anticheat.check.speed:
    description: Dovoluje hráčům používat speed hacky
    default: false
  anticheat.check.vclip:
    description: Allow players clipovat skrz stěny
    default: false
  anticheat.check.spider:
    description: Dovluje hráčům šplhat non-climbable plochy
    default: false
  anticheat.check.nofall:
    description: Dovluje hráčům nofall
    default: false
  anticheat.check.fastbow:
    description: Dovluje hráčům střílet  instantně
    default: false
  anticheat.check.fasteat:
    description: Dovluje hráčům jíst instantně
    default: false
  anticheat.check.fastheal:
    description: Dovluje hráčům healovat instantně
    default: false
  anticheat.check.killaura:
    description: Dovoluje hráčům používat killauru
    default: false
  anticheat.check.unicode:
    description: Dovoluje hráčům používat unicode v chatu
    default: false
  anticheat.check.fastprojectile:
    description: Dovluje hráčům spamovat projectily (fastbow etc.)
    default: false
  anticheat.check.itemspam:
    description: Dovoluje hráčům používat inventory drop spam hacky
    default: false
  anticheat.check.fastinventory:
    description: Dovoluje hráčům používat fastloot and similar inventory hacky
    default: false
  anticheat.check.morepackets:
    description: Dovluje hráčům odesílat spoustu movement packetů nebo měnit timer
    default: false
  anticheat.check.badpackets:
    description: Dovluje hráčům odesílat invalid movement packety
    default: false
  anticheat.check.velocity:
    description: Dovoluje hráčům používat knockback prevention
    default: false
  anticheat.check.criticals:
    description: Dovoluje hráčům používat criticaly
    default: false
  anticheat.check.illegalinteract:
    description: Dovluje hráčům pokládat bloky v neplatných pozicích
    default: false
  anticheat.check.fastladder:
    description: Dovluje hráčům šplhat žebříky rychleji
    default: false
  anticheat.check.aimbot:
    description: Dovoluje hráčům používat aimbot
    default: false
  anticheat.check.strafe:
    description: Dovoluje hráčům používat strafe hacky
    default: false
  anticheat.check.noslow:
    description: Dovoluje hráčům používat NoSlow hacky
    default: false
  anticheat.check.boatfly:
    description: Dovoluje hráčům používat boat fly hacky
    default: false
  anticheat.check.exempt:
    description: Úplné osvobození od kontrol
    default: false
    children:
      anticheat.check.flight: true
      anticheat.check.elytrafly: true
      anticheat.check.waterwalk: true
      anticheat.check.fastplace: true
      anticheat.check.chatspam: true
      anticheat.check.commandspam: true
      anticheat.check.sprint: true
      anticheat.check.sneak: true
      anticheat.check.speed: true
      anticheat.check.vclip: true
      anticheat.check.spider: true
      anticheat.check.nofall: true
      anticheat.check.fastbow: true
      anticheat.check.fasteat: true
      anticheat.check.fastheal: true
      anticheat.check.killaura: true
      anticheat.check.fastprojectile: true
      anticheat.check.itemspam: true
      anticheat.check.fastinventory: true
      anticheat.check.morepackets: true
      anticheat.check.badpackets: true
      anticheat.check.velocity: true
      anticheat.check.criticals: true
      anticheat.check.unicode: true
      anticheat.check.illegalinteract: true
      anticheat.check.fastladder: true
      anticheat.check.aimbot: true
      anticheat.check.strafe: true
      anticheat.check.noslow: true
      anticheat.check.boatfly: true
